develope

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,6 +14,13 @@ jobs:
           keys:
             - v2-dependencies-{{ checksum "requirements.txt" }}
       - run:
+          name: Check for requirements.txt
+          command: |
+            if [ ! -f requirements.txt ]; then
+              echo "Error: requirements.txt not found!"
+              exit 1
+            fi
+      - run:
           name: Set PYTHONPATH
           command: echo 'export PYTHONPATH=$PYTHONPATH:/home/circleci/project' >> $BASH_ENV
       - run:
@@ -37,6 +44,13 @@ jobs:
       - restore_cache:
           keys:
             - v2-dependencies-{{ checksum "requirements.txt" }}
+      - run:
+          name: Check for requirements.txt
+          command: |
+            if [ ! -f requirements.txt ]; then
+              echo "Error: requirements.txt not found!"
+              exit 1
+            fi
       - run:
           name: Set PYTHONPATH
           command: echo 'export PYTHONPATH=$PYTHONPATH:/home/circleci/project' >> $BASH_ENV
@@ -71,6 +85,13 @@ jobs:
           keys:
             - v2-dependencies-{{ checksum "requirements.txt" }}
       - run:
+          name: Check for requirements.txt
+          command: |
+            if [ ! -f requirements.txt ]; then
+              echo "Error: requirements.txt not found!"
+              exit 1
+            fi
+      - run:
           name: Set PYTHONPATH
           command: echo 'export PYTHONPATH=$PYTHONPATH:/home/circleci/project' >> $BASH_ENV
       - run:
@@ -95,7 +116,6 @@ jobs:
             - ~/.cache/pip
             - venv
           key: v2-dependencies-{{ checksum "requirements.txt" }}
-
 
 workflows:
   version: 2
